example:
	d++ matrix_example.dpp 	-L/usr/local/lib/libgretl-1.0.so --include-path=/usr/include/glib-2.0 --include-path=/usr/lib/x86_64-linux-gnu/glib-2.0/include --include-path=/usr/local/include/gretl/

