example:
	d++ -c --keep-d-files -fPIC --include-path=/usr/include/octave-4.2.2/octave/.. --include-path=/usr/include/octave-4.2.2/octave --include-path=/usr/include/hdf5/serial mypow3.dpp
	dmd -shared -defaultlib=libphobos2.so -of=mypow3.mex mypow3.o -L/usr/lib/x86_64-linux-gnu/liboctinterp.so -L/usr/lib/x86_64-linux-gnu/liboctave.so
